backend:
  name: test-repo
  branch: main

publish_mode: editorial_workflow
media_folder: "static/images"
public_folder: "images"

locale: "pt-BR"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
